apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: jenkinsci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkinsci
  template:
    metadata:
      labels:
        app: jenkinsci
    spec:
      containers:
        - name: jenkinsci
          image: curtwphillips/jenkinsci
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: jenkinsci
spec:
  type: NodePort
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      nodePort: 32121
  selector:
    app: jenkinsci
